#!/usr/bin/python
# coding=utf8

incredits="""	">LIST PERSONNEL:" "CreditsOutroText"
	"Michael Abrash" "CreditsOutroText"
	"Mike Ambinder" "CreditsOutroText"
	"Matthew An" "CreditsOutroText"
	"Elizabeth Andrade" "CreditsOutroText"
	"Max Aristov" "CreditsOutroText"
	"Ricardo Ariza" "CreditsOutroText"
	"Gautam Babbar" "CreditsOutroText"
	"Ted Backman" "CreditsOutroText"
	"William Bacon" "CreditsOutroText"
	"Jeff Ballinger" "CreditsOutroText"
	"Ken Banks" "CreditsOutroText"
	"Aaron Barber" "CreditsOutroText"
	"Jeep Barnett" "CreditsOutroText"
	"John Bartkiw" "CreditsOutroText"
	"Mark Behm" "CreditsOutroText"
	"Mike Belzer" "CreditsOutroText"
	"Caleb Benefiel" "CreditsOutroText"
	"Jeremy Bennett" "CreditsOutroText"
	"Dan Berger" "CreditsOutroText"
	"Yahn Bernier" "CreditsOutroText"
	"Amanda Beste" "CreditsOutroText"
	"Ken Birdwell" "CreditsOutroText"
	"Derrick Birum" "CreditsOutroText"
	"Mike Blaszczak" "CreditsOutroText"
	"Iestyn Bleasdale-Shepherd" "CreditsOutroText"
	"Steve Bond" "CreditsOutroText"
	"Matt Boone" "CreditsOutroText"
	"Michael Booth" "CreditsOutroText"
	"Antoine Bourdon" "CreditsOutroText"
	"Christopher Boyd" "CreditsOutroText"
	"Jason Brashill" "CreditsOutroText"
	"Charlie Brown" "CreditsOutroText"
	"Jeff Brown" "CreditsOutroText"
	"Tom Bui" "CreditsOutroText"
	"Charlie Burgin" "CreditsOutroText"
	"Andrew Burke" "CreditsOutroText"
	"Augusta Butlin" "CreditsOutroText"
	"Tobin Buttram" "CreditsOutroText"
	"Liz Cambridge" "CreditsOutroText"
	"Heather Campbell" "CreditsOutroText"
	"Matt Campbell" "CreditsOutroText"
	"Chris Carollo" "CreditsOutroText"
	"Dario Casali" "CreditsOutroText"
	"Matt Charlesworth" "CreditsOutroText"
	"Pongthep Bank Charnchaichujit" "CreditsOutroText"
	"Grégoire Cherlin" "CreditsOutroText"
	"Chris Chin" "CreditsOutroText"
	"Kurtis Chinn" "CreditsOutroText"
	"Jared Christen" "CreditsOutroText"
	"Doug Church" "CreditsOutroText"
	"Jess Cliffe" "CreditsOutroText"
	"Phil Co" "CreditsOutroText"
	"John Cook" "CreditsOutroText"
	"Christen Coomer" "CreditsOutroText"
	"Greg Coomer" "CreditsOutroText"
	"Michael Coupland" "CreditsOutroText"
	"Scott Dalton" "CreditsOutroText"
	"Kerry Davis" "CreditsOutroText"
	"Kyle Davis" "CreditsOutroText"
	"Bruce Dawson" "CreditsOutroText"
	"Joe Demers" "CreditsOutroText"
	"Ariel Diaz" "CreditsOutroText"
	"Viktoria Dillon" "CreditsOutroText"
	"Quintin Doroquez" "CreditsOutroText"
	"Chris Douglass" "CreditsOutroText"
	"Shanon Drone" "CreditsOutroText"
	"Laura Dubuk" "CreditsOutroText"
	"Mike Dunkle" "CreditsOutroText"
	"Fletcher Dunn" "CreditsOutroText"
	"Mike Durand" "CreditsOutroText"
	"Marcus Egan" "CreditsOutroText"
	"Zach Eller" "CreditsOutroText"
	"Dhabih Eng" "CreditsOutroText"
	"Brett English" "CreditsOutroText"
	"Miles Estes" "CreditsOutroText"
	"Chet Faliszek" "CreditsOutroText"
	"Al Farnsworth" "CreditsOutroText"
	"Dave Feise" "CreditsOutroText"
	"Adrian Finol" "CreditsOutroText"
	"Bill Fletcher" "CreditsOutroText"
	"Adam Foster" "CreditsOutroText"
	"Zachary Franks" "CreditsOutroText"
	"Reuben Fries" "CreditsOutroText"
	"Stephane Gaudette" "CreditsOutroText"
	"Rich Geldreich" "CreditsOutroText"
	"Vitaliy Genkin" "CreditsOutroText"
	"Derrick Gennrich" "CreditsOutroText"
	"Cayle George" "CreditsOutroText"
	"Henry Goffin" "CreditsOutroText"
	"Paul Graham" "CreditsOutroText"
	"Chris Green" "CreditsOutroText"
	"Bronwen Grimes" "CreditsOutroText"
	"Chris Grinstead" "CreditsOutroText"
	"John Guthrie" "CreditsOutroText"
	"Aaron Halifax" "CreditsOutroText"
	"Jeff Hameluck" "CreditsOutroText"
	"Joe Han" "CreditsOutroText"
	"Romy Hatfield" "CreditsOutroText"
	"Nate Heller" "CreditsOutroText"
	"Don Holden" "CreditsOutroText"
	"Jason Holtman" "CreditsOutroText"
	"Eric Hope" "CreditsOutroText"
	"Gray Horsfield" "CreditsOutroText"
	"Keith Huggins" "CreditsOutroText"
	"Jim Hughes" "CreditsOutroText"
	"Brandon Idol" "CreditsOutroText"
	"Brian Jacobson" "CreditsOutroText"
	"Lars Jensvold" "CreditsOutroText"
	"Burton Johnsey" "CreditsOutroText"
	"Erik Johnson" "CreditsOutroText"
	"Rick Johnson" "CreditsOutroText"
	"Adrian Johnston" "CreditsOutroText"
	"Jakob Jungels" "CreditsOutroText"
	"Neil Kaethler" "CreditsOutroText"
	"Rich Kaethler" "CreditsOutroText"
	"Steve Kalning" "CreditsOutroText"
	"Kristopher Katz" "CreditsOutroText"
	"Aaron Kearly" "CreditsOutroText"
	"Emily Kent" "CreditsOutroText"
	"Iikka Keränen" "CreditsOutroText"
	"Andrew Kim" "CreditsOutroText"
	"David Kircher" "CreditsOutroText"
	"Eric Kirchmer" "CreditsOutroText"
	"Zoid Kirsch" "CreditsOutroText"
	"Tejeev Kohli" "CreditsOutroText"
	"Peter Konig" "CreditsOutroText"
	"Ted Kosmatka" "CreditsOutroText"
	"Alden Kroll" "CreditsOutroText"
	"Laure Lacascade" "CreditsOutroText"
	"Marc Laidlaw" "CreditsOutroText"
	"Stefan Landvogt" "CreditsOutroText"
	"Jeff Lane" "CreditsOutroText"
	"Keith Lango" "CreditsOutroText"
	"Tim Larkin" "CreditsOutroText"
	"Liam Lavery" "CreditsOutroText"
	"Jinwoo Lee" "CreditsOutroText"
	"Isabelle Lemay" "CreditsOutroText"
	"Tom Leonard" "CreditsOutroText"
	"Justin Lesamiz" "CreditsOutroText"
	"Jeff Lind" "CreditsOutroText"
	"Jon Lippincott" "CreditsOutroText"
	"Jane Lo" "CreditsOutroText"
	"Matt Logue" "CreditsOutroText"
	"Doug Lombardi" "CreditsOutroText"
	"Andrew Loomer" "CreditsOutroText"
	"Richard Lord" "CreditsOutroText"
	"Realm Lovejoy" "CreditsOutroText"
	"Joe Ludwig" "CreditsOutroText"
	"Scott Ludwig" "CreditsOutroText"
	"Randy Lundeen" "CreditsOutroText"
	"Roger Lundeen" "CreditsOutroText"
	"Scott Lynch" "CreditsOutroText"
	"Antonello Maddalena" "CreditsOutroText"
	"Ido Magal" "CreditsOutroText"
	"Nick Maggiore" "CreditsOutroText"
	"Yasser Malaika" "CreditsOutroText"
	"Connor Malone" "CreditsOutroText"
	"Alexander Mark" "CreditsOutroText"
	"Michael Marcus" "CreditsOutroText"
	"John McCaskey" "CreditsOutroText"
	"Patrick McClard" "CreditsOutroText"
	"Noel McGinn" "CreditsOutroText"
	"Hamish McKenzie" "CreditsOutroText"
	"Gary McTaggart" "CreditsOutroText"
	"Sergiy Migdalskiy" "CreditsOutroText"
	"Jason Mitchell" "CreditsOutroText"
	"Caroline Müller" "CreditsOutroText"
	"Kyle Monroe" "CreditsOutroText"
	"Mike Morasky" "CreditsOutroText"
	"John Morello II" "CreditsOutroText"
	"Chandler Murch" "CreditsOutroText"
	"Jim Murray" "CreditsOutroText"
	"Marc Nagel" "CreditsOutroText"
	"Olivier Nallet" "CreditsOutroText"
	"Arsenio N. Navarro II" "CreditsOutroText"
	"Dina Nelson" "CreditsOutroText"
	"Gabe Newell" "CreditsOutroText"
	"Milton Ngan" "CreditsOutroText"
	"Aaron Nicholls" "CreditsOutroText"
	"Matt Nickerson" "CreditsOutroText"
	"Andy Nisbet" "CreditsOutroText"
	"Michael Avon Oeming" "CreditsOutroText"
	"Martin Otten" "CreditsOutroText"
	"Corey Peters" "CreditsOutroText"
	"Christine Phelan" "CreditsOutroText"
	"Jay Pinkerton" "CreditsOutroText"
	"DJ Powers" "CreditsOutroText"
	"Karen Prell" "CreditsOutroText"
	"Matt Pritchard" "CreditsOutroText"
	"Bay Raitt" "CreditsOutroText"
	"Lindsay Randall" "CreditsOutroText"
	"Alireza Razmpoosh" "CreditsOutroText"
	"Tristan Reidford" "CreditsOutroText"
	"Brandon Reinhart" "CreditsOutroText"
	"Alfred Reynolds" "CreditsOutroText"
	"Matt Rhoten" "CreditsOutroText"
	"Mark Richardson" "CreditsOutroText"
	"Garret Rickey" "CreditsOutroText"
	"Dave Riller" "CreditsOutroText"
	"Ted Rivera" "CreditsOutroText"
	"Christian Rivers" "CreditsOutroText"
	"Erik Robson" "CreditsOutroText"
	"Joe Rohde" "CreditsOutroText"
	"Elan Ruskin" "CreditsOutroText"
	"Matthew Russell" "CreditsOutroText"
	"Jason Ruymen" "CreditsOutroText"
	"Phillip Saltzman" "CreditsOutroText"
	"Michael Sartain" "CreditsOutroText"
	"Dave Saunders" "CreditsOutroText"
	"David Sawyer" "CreditsOutroText"
	"Marc Scaparro" "CreditsOutroText"
	"Thorsten Scheuermann" "CreditsOutroText"
	"Florent Schiffer" "CreditsOutroText"
	"Wade Schin" "CreditsOutroText"
	"Matthew Scott" "CreditsOutroText"
	"Gregory Sedgwick" "CreditsOutroText"
	"Aaron Seeler" "CreditsOutroText"
	"Chris Shambaugh" "CreditsOutroText"
	"Taylor Sherman" "CreditsOutroText"
	"James Shin" "CreditsOutroText"
	"Joel Shoop" "CreditsOutroText"
	"Ivan Simoncini" "CreditsOutroText"
	"Justin Skinner" "CreditsOutroText"
	"Eric Smith" "CreditsOutroText"
	"Jacob J. Smith" "CreditsOutroText"
	"Jeff Sorensen" "CreditsOutroText"
	"David Speyrer" "CreditsOutroText"
	"Kutta Srinivasan" "CreditsOutroText"
	"Mellissa Stanfield" "CreditsOutroText"
	"Jay Stelly" "CreditsOutroText"
	"Jenny Stendahl" "CreditsOutroText"
	"Mike Stevens" "CreditsOutroText"
	"Eric Strand" "CreditsOutroText"
	"Jonathan Sutton" "CreditsOutroText"
	"Anna Sweet" "CreditsOutroText"
	"Eric Tams" "CreditsOutroText"
	"Ryan Thorlakson" "CreditsOutroText"
	"Kelly Thornton" "CreditsOutroText"
	"Paul G. Thuriot" "CreditsOutroText"
	"Greg Towner" "CreditsOutroText"
	"Ray Ueno" "CreditsOutroText"
	"Jeff Unay" "CreditsOutroText"
	"Doug Valente" "CreditsOutroText"
	"Bill Van Buren" "CreditsOutroText"
	"Gabe Van Engel" "CreditsOutroText"
	"Alex Vlachos" "CreditsOutroText"
	"Robin Walker" "CreditsOutroText"
	"Eric Wanless" "CreditsOutroText"
	"Chad Weaver" "CreditsOutroText"
	"Joshua Weier" "CreditsOutroText"
	"Chris Welch" "CreditsOutroText"
	"Thad Wharton" "CreditsOutroText"
	"Karl Whinnie" "CreditsOutroText"
	"Andrea Wicklund" "CreditsOutroText"
	"Andrew Wolf" "CreditsOutroText"
	"Erik Wolpaw" "CreditsOutroText"
	"Doug Wood" "CreditsOutroText"
	"Matt T. Wood" "CreditsOutroText"
	"Danika Wright" "CreditsOutroText"
	"Matt Wright" "CreditsOutroText"
	"Pieter Wycoff" "CreditsOutroText"
	"Shawn Zabecki" "CreditsOutroText"
	"Torsten Zabka" "CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
 	">VOICES:" "CreditsOutroText"
	"Ellen McLain - GlaDOS, Turrets" "CreditsOutroText"
	"Stephen Merchant - Wheatley" "CreditsOutroText"
	"J.K. Simmons - Cave Johnson" "CreditsOutroText"
	"Joe Michaels - Announcer" "CreditsOutroText"
	"Nolan North - Cores," "CreditsOutroText"
	"              Defective Turrets" "CreditsOutroText"
	"Dee Bradley Baker - Atlas," "CreditsOutroText"
	"                    P-Body" "CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	">THANKS FOR THE USE" "CreditsOutroText"
	">OF THEIR FACE:" "CreditsOutroText"
	"Alesia Glidewell - Chell" "CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	">SONGS:" "CreditsOutroText"
	"'Exile Vilify'" "CreditsOutroText"
	"Written by Matthew Berninger" "CreditsOutroText"
	"and Aaron Dessner" "CreditsOutroText"
	"Published by" "CreditsOutroText"
	"Val Jester Music (ASCAP)" "CreditsOutroText"
	"and ABD 13 Music (ASCAP)" "CreditsOutroText"
	"administered by Bug" "CreditsOutroText"
	"Performed by The National" "CreditsOutroText"
	" "	"CreditsOutroText"
	"'Still Alive' by:" "CreditsOutroText"
	"Jonathan Coulton" "CreditsOutroText"
	" "	"CreditsOutroText"
	"'Want You Gone' by:" "CreditsOutroText"
	"Jonathan Coulton" "CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	">VOICE RECORDING:" "CreditsOutroText"
	"Pure Audio, Seattle, WA" "CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	">TRANSLATIONS:" "CreditsOutroText"
	"SDL" "CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	">SPECIAL THANKS TO:" "CreditsOutroText"
	"Alienware" "CreditsOutroText"
	"ATI" "CreditsOutroText"
	"Dell" "CreditsOutroText"
	"Falcon Northwest" "CreditsOutroText"
	"Havok" "CreditsOutroText"
	"Sam Gray" "CreditsOutroText"
	"Jamie Hunsdale" "CreditsOutroText"
	" "	"CreditsOutroText"
	">PHOTO CREDIT OF EARTH:" "CreditsOutroText"
	"NASA" "CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText"
	" "	"CreditsOutroText" """


inlyricstext="""	"[2.0]Forms FORM-29827281-12-2:"	"CreditsOutroText"
	"[2.0]Notice of Dismissal"	"CreditsOutroText"
	"[2.00]^"	"CreditsOutroText"
	"[1.8]Well here we are again"	"CreditsOutroText"
	"[0.6] "	"CreditsOutroText"
	"[1.98]It's always such a pleasure"	"CreditsOutroText"
	"[0.6] "	"CreditsOutroText"
	"[1.43]Remember when you tried"	"CreditsOutroText"
	"[0.34]*to " "CreditsOutroText"
	"[1.82]kill me twice?"	"CreditsOutroText"
	"[1.1] "	"CreditsOutroText"
	"[1.8]Oh how we laughed and laughed"	"CreditsOutroText"
	"[0.3] "	"CreditsOutroText"
	"[2.0]Except I wasn't laughing"	"CreditsOutroText"
	"[0.5] "	"CreditsOutroText"
	"[0.69]*Under the"	"CreditsOutroText"
	"[1.49] circumstances"	"CreditsOutroText"
	"[0.0] "	"CreditsOutroText"
	"[0.81]*I've been "	"CreditsOutroText"
	"[1.26]*shockingly "	"CreditsOutroText"
	"[0.33]nice"	"CreditsOutroText"
	"[0.9] "	"CreditsOutroText"
	"[0.3]&"	"CreditsOutroText"
	"[2.12]You want your freedom?"	"CreditsOutroText"
	"[0.2] "	"CreditsOutroText"
	"[1.0]Take it"	"CreditsOutroText"
	"[0.98] "	"CreditsOutroText"
	"[2.7]That's what I'm counting on"	"CreditsOutroText"
	"[2.5]^"	"CreditsOutroText"
	"[0.95]*I used to "	"CreditsOutroText"
	"[1.13]*want you "	"CreditsOutroText"
	"[0.73]dead"	"CreditsOutroText"
	"[0.3]but"	"CreditsOutroText"
	"[0.39] "	"CreditsOutroText"
	"[1.4]*Now I only "	"CreditsOutroText"
	"[0.922]*want you "	"CreditsOutroText"
	"[0.7]gone"	"CreditsOutroText"
	"[3.6] "	"CreditsOutroText"
	"[0.9]&"	"CreditsOutroText"
	"[1.741]She was a lot like you"	"CreditsOutroText"
	"[0.800] "	"CreditsOutroText"
	"[1.858](Maybe not quite as heavy)"	"CreditsOutroText"
	"[0.65] "	"CreditsOutroText"
	"[1.77]*Now little Caroline "	"CreditsOutroText"
	"[1.9]is in here too"	"CreditsOutroText"
	"[0.900] "	"CreditsOutroText"
	"[1.985]One day they woke me up"	"CreditsOutroText"
	"[0.51] "	"CreditsOutroText"
	"[2.12]So I could live forever"	"CreditsOutroText"
	"[0.200] "	"CreditsOutroText"
	"[1.75]It's such a shame the same"	"CreditsOutroText"
	"[3.19]will never happen to you"	"CreditsOutroText"
	"[0.50] "	"CreditsOutroText"
	"[0.01]&"	"CreditsOutroText"
	"[0.09]Severance Package Details:"	"CreditsOutroText"
	"[0.01]^"	"CreditsOutroText"
	"[0.88]You've got your "	"CreditsOutroText"
	"[1.25]short sad "	"CreditsOutroText"
	"[0.69]*life "	"CreditsOutroText"
	"[1.5]left"	"CreditsOutroText"
	"[0.48] "	"CreditsOutroText"
	"[2.5]That's what I'm counting on"	"CreditsOutroText"
	"[2.1] "	"CreditsOutroText"
	"[3.29]I'll let you get right to it"	"CreditsOutroText"
	"[0.3] "	"CreditsOutroText"
	"[1.4]*Now I only "	"CreditsOutroText"
	"[0.922]*want you "	"CreditsOutroText"
	"[0.7]gone"	"CreditsOutroText"
	"[3.968] "	"CreditsOutroText"
	"[1.1]&"	"CreditsOutroText"
	"[1.77]Goodbye my only friend"	"CreditsOutroText"
	"[0.62] "	"CreditsOutroText"
	"[0.24]*Oh,"	"CreditsOutroText"
	"[0.383]* "	"CreditsOutroText"
	"[1.34]did you think I meant you?"	"CreditsOutroText"
	"[0.57] "	"CreditsOutroText"
	"[1.16]That would be funny"	"CreditsOutroText"
	"[0.38] "	"CreditsOutroText"
	"[0.95]*if it weren't "	"CreditsOutroText"
	"[0.905]so sad"	"CreditsOutroText"
	"[1.21] "	"CreditsOutroText"
	"[1.79]Well you have been replaced"	"CreditsOutroText"
	"[0.61] "	"CreditsOutroText"
	"[2.08]I don't need anyone now"	"CreditsOutroText"
	"[0.24] "	"CreditsOutroText"
	"[2.02]When I delete you maybe"	"CreditsOutroText"
	"[0.1] "	"CreditsOutroText"
	"[2.55][REDACTED]"	"CreditsOutroText"
	"[0.70] "	"CreditsOutroText"
	"[0.3]&"	"CreditsOutroText"
	"[1.567]*Go make some new "	"CreditsOutroText"
	"[2.02]disaster"	"CreditsOutroText"
	"[1.27] "	"CreditsOutroText"
	"[2.5]That's what I'm counting on"	"CreditsOutroText"
	"[2.15] "	"CreditsOutroText"
	"[3.36]You're someone else's problem"	"CreditsOutroText"
	"[2.35]*Now I only want you"	"CreditsOutroText"
	"[0.10]* "	"CreditsOutroText"
	"[1.16]gone"	"CreditsOutroText"
	"[1.18] "	"CreditsOutroText"
	"[2.358]*Now I only want you"	"CreditsOutroText"
	"[0.10]* "	"CreditsOutroText"
	"[1.16]gone"	"CreditsOutroText"
	"[1.15] "	"CreditsOutroText"
	"[1.88]*Now I only want"	"CreditsOutroText"
	"[0.57]* "	"CreditsOutroText"
	"[0.3]*you"	"CreditsOutroText"
	"[0.01]&"	"CreditsOutroText"
	"[0.01]^"	"CreditsOutroText"
	"[0.01]^"	"CreditsOutroText"
	"[0.01]^"	"CreditsOutroText"
	"[0.01]^"	"CreditsOutroText"
	"[0.04]^"	"CreditsOutroText"
	"[1.16]gone "	"CreditsOutroText"
"""

credits=[]
for line in incredits.split('\n'):
	start=line.find('"')
	end=line.find('"',start+1)
	credits.append(line[start+1:end])

lyrics=[]
nextonsameline=0
for line in inlyricstext.split('\n'):
	start=line.find('[')
	stop=line.find(']')
	delay=line[start+1:stop]
	if len(delay)<1:
		delay=0

	start=stop
	stop=line.find('"',start)
	message=line[start+1:stop]

	lyricsline={}
	lyricsline['delay']=delay
	lyricsline['text']=''
	lyricsline['newline']=1
	lyricsline['clear']=0

	if len(message)>0:
		if message[0]=='^':     # newline
			message=message[1:]
			lyricsline['newline']=1
		elif message[0]=='&':       # new page
			message=message[1:]
			lyricsline['clear']=1
		elif message==' ':          # pause
			message=message[1:]
			lyricsline['newline']=0
		elif message[0]=='*':       # next on same line
			message=message[1:]
			lyricsline['newline']=0
		
	lyricsline['text']=message
	
	lyrics.append(lyricsline)

outputlines=[]

outputlines.append('')
outputlines.append('var credits=[')
for line in credits:
    outputlines.append(' "%s",'%line)
outputlines[-1]=outputlines[-1][:-1]
outputlines.append('];')

outputlines.append('')
outputlines.append('var lyrics=[')
for lyric in lyrics:
    outputlines.append(' {')
    outputlines.append('  delay:%s,'%lyric['delay'])
    outputlines.append('  text:"%s",'%lyric['text'])
    outputlines.append('  newline:%i,'%lyric['newline'])
    outputlines.append('  clear:%i'%lyric['clear'])
    outputlines.append('  },')
outputlines[-1]=outputlines[-1][:-1]
outputlines.append('];')


output=file('cake2data.js','w')
output.write('\n'.join(outputlines))
output.close()
